# input_perphect: data/perphect-data/dummy
input_perphect:
  bacteria_df: data/perphect-data/all/bacteria_df.csv
  phages_df: data/perphect-data/all/phages_df.csv
  couples_df: data/perphect-data/all-private-undersampled/couples_df.csv
embeddings_dir: data/embeddings
num_gpu: 1
gpu_id: 3
# use_cached_embeddings: true

phages_embedding_models:
  - name: NT2
    model_name: nucleotide-transformer-v2-50m-multi-species
    strategy:
      name: TruncateStrategy

bacteria_embedding_models:
  - name: NT2
    model_name: nucleotide-transformer-v2-50m-multi-species
    strategy:
      name: TKPertStrategy
      merging_strategy: concat
