input_perphect: data/perphect-data/private_data_set
num_gpu: 1
gpu_id: 0

phages_embedding_models:
  - name: NT2
    params: 
      model_name: nucleotide-transformer-v2-250m-multi-species
    strategy: TopBottomTruncateStrategy
    use_cached_embeddings: auto

bacteria_embedding_models:
  - name: NT2
    params: 
      model_name: nucleotide-transformer-v2-250m-multi-species
    strategy: TopBottomTruncateStrategy
    use_cached_embeddings: auto

classifier:
  name: LinearClassifier
