# Example configuration file for training and evaluating a PBI model.
# You can use this file as a template to create your own configuration files.
# Remember to only use one of the multiple options provided for some parameters (meaning, no repeated keys). If not, only the last one will be considered.

input_perphect: path/to/perphect/data # Basic way to specify the input data. /path/to/perphect/data must contain at least 3 files, bacteria_df.csv, phages_df.csv and couples_df.csv.
input_perphect: # More explicit way to specify the input data files.
  bacteria_df: /path/to/perphect/data/bacteria_df.csv # Path to the bacteria dataframe CSV file. It must contain at least two columns: 'bacterium_id' and 'bacterium_sequence'.
  phages_df: /path/to/perphect/data/phages_df.csv # Path to the phages dataframe CSV file. It must contain at least two columns: 'phage_id' and 'phage_sequence'.
  couples_df: /path/to/perphect/data/couples_df.csv # Path to the couples dataframe CSV file. It must contain at least 3 columns: 'bacterium_id', 'phage_id' and 'interaction_type' (1 if there is an interaction, 0 otherwise).

embeddings_dir: data/embeddings # Directory to store/load the computed embeddings. Default is 'data/embeddings'.
output_dir: output/example_model/ # Directory to store the output results of the model or null if no output is desired. Default is null.

num_gpu: 0 # Use GPU (1) or CPU (0). Default is 0.
gpu_id: 0 # ID of the GPU to use if num_gpu == 1.

torch_num_threads: -1 # Number of threads to use for PyTorch operations. Default is -1 (use all available threads).

training_config:
  do_train: true # Whether to train the model. If false, only compute the embeddings and exit. Default is true.
  epochs: 10 # Number of training epochs. Default is 10.
  learning_rate: 1e-3 # Learning rate for the optimizer. Default is 1e-3.
  weight_decay: 1e-4 # Weight decay (L2 regularization) for the optimizer. Default is 1e-4.
  batch_size: 128 # Batch size for training. Default is 128.

  reduce_dimensionality: "none" # The dimensionality reduction technique to apply to the merged embeddings. If "none", do not use any. Can be either "none" or PCA. Default is "none".
  n_components_bacteria: null # Number of components to keep when reducing the dimensionality of bacteria embeddings. Only used if reduce_dimensionality is not "none". Default is null (keep all components).
  n_components_phages: null # Number of components to keep when reducing the dimensionality of phage embeddings. Only used if reduce_dimensionality is not "none". Default is null (keep all components).

  k_folds_cv: 3 # Number of folds for k-fold cross-validation. Default is 3. Must be >= 2.

  patience_early_stopping: 1000 # Number of epochs with no improvement after which training will be stopped. Default is 1000. To disable early stopping, set this to a very high value.
  monitor_metric_early_stopping: f1 # Metric to monitor for early stopping. Can be either "f1" or "loss". Default is "f1".

  patience_reduce_lr: 1000 # Number of epochs with no improvement after which learning rate will be reduced. Default is 1000. To disable learning rate reduction, set this to a very high value.
  monitor_metric_reduce_lr: f1 # Metric to monitor for learning rate reduction. Can be either "f1" or "loss". Default is "f1".
  multiplying_factor_reduce_lr: 0.5 # Factor by which the learning rate will be reduced. Default is 0.5.

phages_embedding_models: # List of embedding models to use for phage sequences. You can specify multiple models to combine their embeddings.
# name (str): Name of the embedding model to use. Must be a subclass of `AbstractModel`, implemented in `pbi_models.embedders`.
# params (Dict[str, Any]): Specific parameters to initialize the embedding model. They are passed as keyword arguments to the model constructor.
# strategy (StrategyConfig | str): Merging strategy to use when multiple embeddings are generated by this model. If a string, use the default parameters for that strategy. Can be either one string or a parameter with the following format:
#   name (str): Name of the merging strategy to use. Must be a subclass of `AbstractMergerStrategy`, implemented in `pbi_utils.embeddings_merging_strategies`.
#   params (Dict[str, Any]): Specific parameters to initialize the merging strategy. They are passed as keyword arguments to the strategy constructor.
# use_cached_embeddings (CACHED_EMBEDDINGS_OPTION): If true, do not calculate embeddings for this model, use cached ones from `embeddings_dir`. Also, if true, the embedding models will not be loaded, saving time and possible environment problems. If "auto", use cached embeddings if they exist, otherwise compute them. Default is auto.

# Examples:
  - name: NT2 # Nucleotide Transformer 2 model
    params:
      model_name: nucleotide-transformer-v2-250m-multi-species # Model name or path to the pretrained weights.
    strategy: TopBottomTruncateStrategy
    use_cached_embeddings: auto

  - name: MegaDNA
    params: 
      weights_path: data/weights/megaDNA_phage_145M.pt # Automatically downloaded if not set
      get_layer: concat
    strategy: MaxStrategy
    use_cached_embeddings: auto

  - name: DNABERT2
    params: 
      source_code_path: foundation-models-test/DNABERT-2/DNABERT-2-117M/
      max_seq_len: 32768
    strategy: 
      name: TKPertStrategy
      params:
        J: 16
        gamma: 20
        merging_strategy: concat
    use_cached_embeddings: auto

bacteria_embedding_models: # List of embedding models to use for bacteria sequences. You can specify multiple models to combine their embeddings.
# Same format as phages_embedding_models.

# Examples:
  - name: NT2
    params: 
      model_name: nucleotide-transformer-v2-250m-multi-species
    strategy: TopBottomTruncateStrategy
    use_cached_embeddings: true

  - name: MegaDNA
    params: 
      weights_path: data/weights/megaDNA_phage_145M.pt
      get_layer: concat
    strategy: BottomTruncateStrategy
    use_cached_embeddings: true

  - name: DNABERT2
    params: 
      source_code_path: foundation-models-test/DNABERT-2/DNABERT-2-117M/
      max_seq_len: 32768
    strategy: TopBottomTruncateStrategy
    use_cached_embeddings: true


# Classifier configuration: 
# Attributes:
# name (str): Name of the classifier model to use. Must be a subclass of `AbstractClassifier`, implemented in `pbi_models.classifiers`.
# params (Dict[str, Any]): Specific parameters to initialize the classifier model. They are passed as keyword arguments to the model constructor. To see the available parameters for each classifier, check their implementation in the `pbi_models.classifiers` module.

# Examples: 
classifier: 
  name: MLPClassifier
  params:
    bacterium_mlp_sizes: [64]
    phage_mlp_sizes: [128, 64]
    dense_dim: 100
    dropout: 0.2

classifier: 
  name: BasicMLPClassifier
  params:
    mlp_params: [256, 128]
    dropout: 0.4

classifier:
  name: LinearClassifier

classifier:
  name: SklearnClassifier
  params:
    sklearn_model_name: RandomForestClassifier
    sklearn_model_params:
      n_estimators: 200
      max_features: null
      max_leaves: 63
      grow_policy: depthwise
      booster: gbtree
      tree_method: hist
      verbosity: 1
      n_jobs: -1

classifier:
  name: SklearnClassifier
  params:
    sklearn_model_name: LGBMClassifier
    sklearn_model_params:
      num_leaves: 63
      n_estimators: 1000
      max_bin: 512
      force_col_wise: true
      n_jobs: -1