# input_perphect: data/perphect-data/dummy
input_perphect:
  bacteria_df: data/perphect-data/predphi/bacteria_sequences.csv
  phages_df: data/perphect-data/predphi/bacteriophages_sequences.csv
  couples_df: data/perphect-data/predphi/predphi_train_dataset.csv
# input_perphect: data/PBIP/perphect_format/all_undersampled

embeddings_dir: data/embeddings-pbip
output_dir: output/pbip/ # Comment line to disable output
num_gpu: 1
gpu_id: 3
# torch_num_threads: 1

training_config:
  # do_train: true
  epochs: 100
  learning_rate: 1e-3
  # weight_decay: 1e-4
  batch_size: 256

  # reduce_dimensionality: PCA
  # n_components_bacteria: 382
  # n_components_phages: 382

  # patience_reduce_lr: 10
  # monitor_metric_reduce_lr: f1
  # multiplying_factor_reduce_lr: 0.5


  k_folds_cv: 10

phages_embedding_models:
  - name: NT2
    params: 
      model_name: nucleotide-transformer-v2-250m-multi-species
    strategy: TKPertStrategy
    use_cached_embeddings: true

  - name: MegaDNA
    params: 
      weights_path: data/weights/megaDNA_phage_145M.pt
      get_layer: concat
    strategy: TopBottomTruncateStrategy
    use_cached_embeddings: true

  - name: DNABERT2
    params: 
      source_code_path: DNABERT-2-117M/
      max_seq_len: 16384
    strategy: TKPertStrategy
    use_cached_embeddings: true

bacteria_embedding_models:
  - name: NT2
    params: 
      model_name: nucleotide-transformer-v2-250m-multi-species
    strategy: TruncateStrategy
    use_cached_embeddings: true

  - name: MegaDNA
    params: 
      weights_path: data/weights/megaDNA_phage_145M.pt
      get_layer: concat
    strategy: TruncateStrategy
    use_cached_embeddings: true

  - name: DNABERT2
    params: 
      source_code_path: DNABERT-2-117M/
      max_seq_len: 16384
    strategy: BottomTruncateStrategy
    use_cached_embeddings: true

# classifier: $CLASSIFIER

classifier: 
  name: MLPClassifier
  params:
    bacterium_mlp_sizes: [256, 128, 64]
    phage_mlp_sizes: [256, 128, 64]
    dense_dim: 128
    dropout: 0.4

# classifier: 
#   name: BasicMLPClassifier
#   params:
#     mlp_params: [256, 128]
#     dropout: 0.4

# classifier:
#   name: LinearClassifier

# classifier:
#   name: BasicClassifier

# classifier:
#   name: SklearnClassifier
#   params:
#     sklearn_model_name: RandomForestClassifier
#     sklearn_model_params:
#       n_estimators: 200
#       max_features: null
#       # max_leaves: 63
#       # grow_policy: depthwise # depthwise lossguide
#       # booster: gbtree # gbtree gblinear dart
#       # tree_method: hist # exact approx hist
#       # verbosity: 1
#       n_jobs: -1

# classifier:
#   name: SklearnClassifier
#   params:
#     sklearn_model_name: XGBClassifier
#     sklearn_model_params:
#       max_depth: 4
#       learning_rate: 0.03
#       subsample: 0.7
#       colsample_bytree: 0.7
#       n_estimators: 500
#       reg_alpha: 8
#       reg_lambda: 2
#       tree_method: hist
#       gamma: 1
#       n_jobs: -1

# classifier:
#   name: SklearnClassifier
#   params:
#     sklearn_model_name: LGBMClassifier
#     sklearn_model_params:
#       # num_leaves: 63
#       n_estimators: 200
#       # max_bin: 512
#       force_col_wise: true
#       n_jobs: -1