# input_perphect: data/perphect-data/dummy
input_perphect:
  bacteria_df: data/perphect-data/all/bacteria_df.csv
  phages_df: data/perphect-data/all/phages_df.csv
  couples_df: data/perphect-data/all-private-oversampled/couples_df.csv
embeddings_dir: data/embeddings
# embeddings_dir: data/embeddings-dummy
# output_dir: output/ # Comment line to disable output
num_gpu: 0
gpu_id: 3
# torch_num_threads: 1

training_config:
  # do_train: true
  epochs: 50
  learning_rate: 1e-3
  weight_decay: 0
  batch_size: 256

  reduce_dimensionality: PCA
  n_components_bacteria: 500
  n_components_phages: 500

  k_folds_cv: 10

  patience_early_stopping: 100 # Disabled
  monitor_metric_early_stopping: f1

  patience_reduce_lr: 100 # Disabled
  monitor_metric_reduce_lr: f1
  multiplying_factor_reduce_lr: 0.5

phages_embedding_models:
  - name: NT2
    params: 
      model_name: nucleotide-transformer-v2-250m-multi-species
      overlap: 0
    strategy: TopBottomTruncateStrategy
    use_cached_embeddings: true

  - name: MegaDNA
    params: 
      weights_path: data/weights/megaDNA_phage_145M.pt
      get_layer: concat
      overlap: 0
    strategy: MaxStrategy
    use_cached_embeddings: true

  - name: DNABERT2
    params: 
      source_code_path: foundation-models-test/DNABERT-2/DNABERT-2-117M/
      max_seq_len: 32768
      overlap: 0
    strategy: TKPertStrategy
    use_cached_embeddings: true

bacteria_embedding_models:
  - name: NT2
    params: 
      model_name: nucleotide-transformer-v2-250m-multi-species
      overlap: 0
    strategy: TopBottomTruncateStrategy
    use_cached_embeddings: true

  - name: MegaDNA
    params: 
      weights_path: data/weights/megaDNA_phage_145M.pt
      get_layer: concat
      overlap: 0
    strategy: BottomTruncateStrategy
    use_cached_embeddings: true

  - name: DNABERT2
    params: 
      source_code_path: foundation-models-test/DNABERT-2/DNABERT-2-117M/
      max_seq_len: 32768
      overlap: 0
    strategy: TopBottomTruncateStrategy
    use_cached_embeddings: true

# classifier: $CLASSIFIER

# classifier: 
#   name: MLPClassifier
#   params:
#     bacterium_mlp_sizes: [64]
#     phage_mlp_sizes: [128, 64]
#     dense_dim: 100
#     dropout: 0.2

# classifier: 
#   name: BasicMLPClassifier
#   params:
#     mlp_params: [512, 256, 128, 64]
#     dropout: 0.2

# classifier:
#   name: LinearClassifier

# classifier:
#   name: BasicClassifier

# classifier:
#   name: SklearnClassifier
#   params:
#     sklearn_model_name: RandomForestClassifier
#     sklearn_model_params:
#       n_estimators: 200
#       max_features: null
#       # max_leaves: 63
#       # grow_policy: depthwise # depthwise lossguide
#       # booster: gbtree # gbtree gblinear dart
#       # tree_method: hist # exact approx hist
#       # verbosity: 1
#       n_jobs: -1

classifier:
  name: SklearnClassifier
  params:
    sklearn_model_name: LGBMClassifier
    sklearn_model_params:
      num_leaves: 63
      n_estimators: 1000
      max_bin: 512
      force_col_wise: true
      n_jobs: -1