input_perphect:
  bacteria_df: data/perphect-data/all/bacteria_df.csv
  phages_df: data/perphect-data/all/phages_df.csv
  couples_df: data/perphect-data/all-private-oversampled/couples_df.csv
embeddings_dir: data/embeddings
num_gpu: 1
gpu_id: 1
use_cached_embeddings: true
# torch_num_threads: 1

training_config:
  # do_train: true
  epochs: 10
  learning_rate: 1e-3
  weight_decay: 1e-4
  batch_size: 256

  k_folds_cv: 2

  patience_early_stopping: 10
  monitor_metric_early_stopping: f1

  patience_reduce_lr: 5
  monitor_metric_reduce_lr: f1
  multiplying_factor_reduce_lr: 0.5


phages_embedding_models:
  - name: NT2
    params: 
      model_name: nucleotide-transformer-v2-50m-multi-species
      overlap: 0
    strategy: TruncateStrategy

bacteria_embedding_models:
  - name: NT2
    params: 
      model_name: nucleotide-transformer-v2-50m-multi-species
      overlap: 0
    strategy: TruncateStrategy

# classifier: 
#   name: CNNClassifier
#   params:
#     bacterium_conv_params: "[(64, 3, 5), (32, 10, 5), (32, 10, 5)]"
#     phage_conv_params: "[(64, 3, 5), (32, 10, 5)]"
#     dense_dim: 100
#     dense_dropout: 0.5

# classifier:
#   name: LinearClassifier

# classifier:
#   name: BasicClassifier

classifier:
  name: SklearnClassifier
  params:
    sklearn_model_name: RandomForestClassifier
    sklearn_model_params:
      n_estimators: 100